### PR TITLE
Zero byte support

### PR DESCRIPTION
**Pull request by nodarius**
Move uploading code from "release" to "flush. Now "release" is responsible for only freeing resources.
"truncate" is implemented.
You can now create zero byte files.

### CODE REVIEW

**Comment by TragicWarrior** [comment]
@nodarius ,

I'm trying to do a build of zero_byte_support and am getting this:

/mnt/stor/work/devel/git-hub/mediafire-fuse/fuse/operations.c: In function ‘mediafirefs_flush’:
/mnt/stor/work/devel/git-hub/mediafire-fuse/fuse/operations.c:930:35: error: unused parameter ‘path’ [-Werror=unused-parameter]
 int mediafirefs_flush(const char *path, struct fuse_file_info *file_info)
                                   ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/mediafire-fuse.dir/fuse/operations.c.o] Error 1
make[1]: *** [CMakeFiles/mediafire-fuse.dir/all] Error 2
make: *** [all] Error 2

**Comment by nodarius** [comment]
OK, this is fixed now

**Comment by TragicWarrior** [comment]
@nodarius , i attempted to edit a file with 256 bytes of random data with mousepad.  after i saved the file i reloaded it.  i had been truncated to zero bytes permanently.  all the content of the file was lost.

**Comment by TragicWarrior** [comment]
@nodarius , it looks like the failure is in the patch upload logic flow:

open flags: 0x8401 /testfile.txt
opening 65ve5l1bnev6m8u with local 427144 and remote 427144
   open[139930705602000] flags: 0x8401 /testfile.txt
   unique: 226, success, outsize: 32
unique: 227, opcode: FLUSH (25), nodeid: 9, insize: 64, pid: 8863
flush[139930705602000]
_fsio_recommend() low source: 4096
fsio source blksz: 131072
fsio_file_read() 0 bytes
state 0
_fsio_recommend() low source: 4096
fsio source blksz: 131072
fsio_file_read() 139930816273040 bytes
state 0
failed to calculate hash
filecache_upload_patch failed
folder_tree_upload_patch failed
   unique: 227, error: -13 (Permission denied), outsize: 16
unique: 228, opcode: WRITE (16), nodeid: 9, insize: 85, pid: 8863
write[139930705602000] 5 bytes to 0 flags: 0x8401
   write[139930705602000] 5 bytes to 0
   unique: 228, success, outsize: 24
unique: 229, opcode: FLUSH (25), nodeid: 9, insize: 64, pid: 8863
flush[139930705602000]
_fsio_recommend() low source: 4096
fsio source blksz: 131072
fsio_file_read() 0 bytes
state 0
_fsio_recommend() low source: 4096
fsio source blksz: 131072
fsio_file_read() 139930831043216 bytes
state 0
failed to calculate hash
filecache_upload_patch failed
folder_tree_upload_patch failed

**Comment by nodarius** [comment]
@TragicWarrior 

Ok here is what I found out so far.

There was an uninitialized variable (old bug), which caused this "failed to calculate hash" error. Easy to fix. No problem. After I fixed this, problems still occur, but of different kind:

When you try to append data to already existing zero byte file, by typing: cat >> file and append some text, it causes to send a patch, like this:
http://pastebin.com/raw.php?i=yNExUJDc

But that fails. After making a "poll/upload" request, you get file error 17 - patch failed. File remains unchanged.

And the second error is this:
When you try to append data to already existing file, which already has some data in it (size > 0), instead of appending, the old data gets deleted and new data is overwritten. 

So far, I found it a little hard to find cause of the second bug, but now I think, after we detect & fix the cause of first error, the second may become easier.

So, the first question: Does the API support patching a zero byte file?

**Comment by TragicWarrior** [comment]
@nodarius , it looks like operations.c ~384 is a no-op.  were you intending to do something else here?

**Comment by nodarius** [comment]
@TragicWarrior 

Right, that commented code was preventing the same file to be opened for writing more than once. So I commented it, but did not fully delete. This way I have right in front of my eyes what I have changed and if these changes cause bugs, it helps me to find them.

I'm going to get rid of such unnecessary codes in future commits, after they've somewhat proven to be bug free. I hope that's ok

**Comment by TragicWarrior** [comment]
@nodarius , OK

**Pull request merged**
